### ISSUE TITLE
为什么我的图色打歌定位是这样的？

### ISSUE THREAD

**Issue by zeronsama** [sharpoverflow/LLHelper_AutoPlay#14]
![如图](https://s2.ax1x.com/2019/01/01/F5A9ns.png)

左上角倒是对上了，可是这里多出来这么多空的，启动后的红圈圈基本上没有对到按键上，还是说这样也可以？

**Comment by sharpoverflow** [comment]
这个是我的失误,在教程中没有写到.
看上去你的模拟器没有调整为1280*720的分辨率,请在设置中调整一下.
注意需要重新制作左上角的图片.
