### ISSUE TITLE
按键时间不对

### ISSUE THREAD

**Issue by PurpleSwords** [sharpoverflow/LLHelper_AutoPlay#5]
我发现在我的电脑上，按键的时间会越来越迟，即画面上的圆圈已经到了该按的地方，而程序还得再等半秒左右，之后的延迟会一直累加。

**Comment by ChiChengXiaoYao** [comment]
目测与按键无关，即运行的时间越长，慢的越多

**Comment by sharpoverflow** [comment]
刚才意识到代码可能写法有问题.
可能是调成正100,或者更高的值,你先试下,有问题可以再留言

**Comment by ChiChengXiaoYao** [comment]
我尝试过录屏，会占用大量的cpu，结果是在卡的时候之后只影响个别按键，之前和之后的按键都会准确的击中note，不会出现延迟累加这种情况。我也观察了很久，感觉就像是我的电脑时间被线性拉伸了一样，游戏时间过去1s，程序的时间只过去0.9s。难道是优先级不够，被其他程序阻断了。今天再次测试，没这问题了，可能那天开了什么程序吧

**Comment by sharpoverflow** [comment]
模拟器开的时间过长会导致延迟,这个我是遇到过的,注意一下这点.
录屏推荐用sharex,不卡.
还有,感兴趣的话尝试下图色打歌工具.

**Comment by ChiChengXiaoYao** [comment]
录屏我用的是BandicamPortable。现在在研究全自动打，感觉没有太大规律。

**Comment by Zhouzerong233** [comment]
感谢分享，我刚刚也遇到了这个问题
